### ISSUE TITLE
Feedback on Donations

### ISSUE THREAD

**Issue by Snake4life** [P-St/Migrate2WinSSHTerm#1]
Since I could not find any channel where I can give some feedback I try my luck here.

v1: Im happy everything is fine, I donated.

v2: Duuuuuude, donation popup feels like some kinda adware scam, pops up every 10-15minutes, so annoying! why do we ( I speak as a user ) even have to donate again and again every year, please take some money but stop with this begging, what the hell. This has nothing to do with donation anymore, you should switch full commercial instead of going like "give me 10 bucks or I will annoy you every 15minutes with my donation popup, but dont forget if you pay 10 bucks you get only 365days till this popup will repop.

nice software anyway. cheers

**Comment by P-St** [comment]
Thanks for using WinSSHTerm and for your feedback. BTW, you can always send me a message by using the contact form on my blog if you have a question or something is unclear.

There is a misunderstanding about v2 here. If you make a donation, this will disable pop-ups for the current version - **forever and always**. There surely won't be pop-ups again after 365 days or so.

Plus you will get pop-up free updates, but only for a limited time period (e.g. 1 year), which to me is quite fair - don't you think?

I don't think this is _begging_, because everyone can use v1 instead, which is absolutely free. As you certainly can imagine I have to regularly spend money for this project (code signing certificates, hosting fees, build hardware). I'm trying to cover these expenses with the donations.

Regards,
Patrick

**Comment by P-St** [comment]
I re-enabled the [feedback page](https://winsshterm.blogspot.com/p/feedback.html) on my blog.

Please don't use GitHub to give feedback for WinSSHTerm as it's only for the migration script. Thanks!
